TOOLCHAIN_PATH = "/usr/local/arm/arm-gcc-3.4.4/gcc-3.4.4-glibc-2.3.3/arm-linux-gnu/bin"

PREFIX = "arm-linux-gnu-"

TARGET = server_t

cc = $(TOOLCHAIN_PATH)/$(PREFIX)gcc

default:
	$(cc) -o $(TARGET) hello_server.c
